require_relative 'human'
require_relative 'wizard'
require_relative 'cat'
require_relative 'dragon'
require_relative 'ancient_tome'
require_relative 'prologue'
require_relative 'climactic_battle_scene'
